# Generated by Django 4.2.26 on 2025-11-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='visit_bookings',
        ),
    ]
